version: '3.8'

networks:
  service_mesh_ingress:
    external: true

volumes:
  portainer:

services:

  agent:
    image: portainer/agent
    networks: &default_networks
      - service_mesh_ingress
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
      restart_policy:
        condition: on-failure
        max_attempts: 5
    environment:
      AGENT_CLUSTER_ADDR: 'tasks.agent'

  portainer:
    image: portainer/portainer
    networks: *default_networks
    volumes:
      - portainer:/data
    command:
      -H tcp://tasks.agent:9001
      --tlsskipverify
      --no-auth
    deploy:
      labels:
        traefik.frontend.rule: 'Host:portainer.localhost'
        traefik.port: 9000
